### PR TITLE
Update go.mod to unbreak imports

### PR DESCRIPTION
**Pull request by HaraldNordgren**
Fixes https://github.com/mhemmings/revenuecat/issues/8.

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
Ping @mhemmings

**Comment by HaraldNordgren** [comment]
@mhemmings Can you take a look here as well? 🤗

The current import path broke after we moved to V2, and there is an issue reported about this.

https://go.dev/blog/v2-go-modules

**Comment by mhemmings** [comment]
New one to me! Thanks for the PR

**Comment by HaraldNordgren** [comment]
@mhemmings, I believe a new tag (patch version) needs to be created as well.

**Pull request merged**
